veusz/veusz

scripts/pyqt_find_translatable
Added --defn optional arguments to accept forced translation function names. These will be used when no definition with the same name is found in the current source file (eg: in case the function is imported from a common module). Global definitions will be overridden by any homonym found in the current source file. 
Eg: 
``pyqt_find_translatable --defn _:foo source.py``
Will consider "_" as defined with "foo" context and default argument ids _(text, disambiguation,context) also if it is not defined in source.py, but only imported from a common module.
=> pyqt_find_translatable accepts forced function names

veusz/document/export.py
This branch fixes image compression for PNG export (which has been broken since at least 9f0810c992 in 2011) and also enables LZW compression for TIFF export.
Using 300 DPI exports of `broken_axis.vsz` to test:
Format | Before | After
---------  | ------------:| --------:
PNG     | 7822679 | 210885
TIFF     | 7808954 | 311248
=> Fix export image compression

ui/exceptionlist.ui, veusz/dialogs/exceptiondialog.py
With this commit, the user will be able to choose to save a crash report to a file, instead of sending it via email.
Our application uses Veusz and, sometimes, it crashes due to our code. So, to avoid you to receive bug reports related to our application, we added the ability to remove the "Send" button from the exception report dialog.
=> Save crash report to file

veusz/windows/plotwindow.py, veusz_pyinst.spec, veusz_windows_pyinst.spec
We had some problems with users that, after a zoom with 'Zoom into graph', didn't understand that they were still in 'Zoom into graph' mode: they thought that selection didn't work any more, given that the cursor was the default one.
To avoid this misunderstanding, we changed the cursor with the cross one.
Probably a better solution would be to find a cursor with an arrow and a magnifying glass, but it isn't included in Qt defaults.
=> cross cursor is selected when in 'Zoom into graph' mode

veusz/widgets/plotters.py
At the moment, if you add a child in a plotter, it is not drawn.
With this change, children of a plotter will be drawn as well.
This is very useful to us, because we created objects related to a curve which have to be children of it.
For example we created a datapoint object used to find and describe some particular points of a curve (minimum, maximum, etc...).
=> Allow to have plotted children of a plotter

scripts/fixup_veusz_dist.sh, veusz/veusz_main.py
This change allows the splash screen text to automatically render at high resolution on HiDPI displays.
=> Change splash screen to use QLabels

veusz/dialogs/export.py, veusz/windows/mainwindow.py
selectedFilter() doesn't seem to exist in pyQt 5. Replaced by selectedNameFilter in the code.
=> fix various crashes with qt5

veusz/windows/plotwindow.py
because of this typo, y axis is not being given the proper maximum value when user is drawing a rectangle.
=> fix typo in zoom rectangle

veusz/windows/plotwindow.py
In the Qt5 version of Veusz, the lateral scrolling in zoomed plots is lost for some hardwares.
According to Qt doc, pixelDelta "is provided on platforms that support high-resolution pixel-based delta values, such as OS X."
On the contrary, angleDelta is always returned.
=> fix shift + scroll not handling every mouses and every trackpads

veusz/helpers/src/qtloops/isnan.h
Hi --
We have been keeping this patch for a while for the OpenBSD package.
With this, Veusz compiles cleanly on OpenBSD.
Thanks.
=> Add OpenBSD to this list.

veusz/helpers/src/threed/objects.cpp, veusz/helpers/src/threed/objects.h, veusz/helpers/src/threed/scene.cpp, veusz/helpers/src/threed/scene.h, veusz/helpers/src/threed/threed.sip
Python’s `id()` function returns memory addresses, which do not fit into signed long on 32-bit systems.
In PyQt 5.12 overflow checking is [enabled by default](https://www.riverbankcomputing.com/news/pyqt-512), so this causes errors like this:
```python
Traceback (most recent call last):
File "tests/runselftest.py", line 307, in <module>
test_unlink=options.test_unlink)
File "tests/runselftest.py", line 236, in runTests
test_unlink=test_unlink)
File "tests/runselftest.py", line 173, in renderVszTest
ifc.Export(outfile)
File "/usr/lib/python3/dist-packages/veusz/document/commandinterface.py", line 778, in Export
e.export()
File "/usr/lib/python3/dist-packages/veusz/document/export.py", line 232, in export
self.exportSelfTest(self.filename)
File …
```
=> Use unsigned long for widget ids instead of signed long

veusz/widgets/key.py
Just a small improvement to exclude some items (cvs list) from the key widget. 
Usefull if you have multiple key widgets in one plot and you want to group the items.
=> Add option to exclude items from key plot

veusz/dialogs/histodata.py, veusz/document/commandinterpreter.py, veusz/document/loader.py, veusz/document/operations.py, veusz/document/svg_export.py, veusz/utils/dates.py
* Fix python 3.9 compatibility for using "U" in open.
* Fix deprecation warning due to invalid escape sequences.
Fixes #371
=> Fix python 3.9 compatibility for using "U" in open

pyqtdistutils.py
This can be tested by installing the latest versions of `sip` and `PyQt5` from PyPI, or by installing `python3-sipbuild` on Debian and `python3-pyqt5`, `pyqt5-dev` from Debian experimental. Then export `SIP_EXE=sip5` when building veusz.
It is a quick solution that allows to support both SIP v4 and v5. When SIP v4 support is no longer needed, it would be better to switch to `sipbuild` API as described in [SIP documentation](https://www.riverbankcomputing.com/static/Docs/sip/index.html).
=> Add support for SIP v5

ui/preferences.ui, veusz/dialogs/preferences.py, veusz/document/doc.py, veusz/setting/settingdb.py
I frequently store veusz files in git repositories.  For that, I do not like it if absolute paths are stored within them.  This branch adds an option in the preferences diaglogue to optionally *not* store import paths in the files.  It defaults to True in line with the current upstream behavior.
=> Add setting to optionally omit import paths in document files

Documents/manual-source/api.rst
Some small fixes for the two Python code blocks in the API doc page, section on Translating old to new style.
Maybe in an older version of the docs or Sphinx the quadruple backslashes were necessary, but now all four are passing into both the compiled [HTML](https://veusz.github.io/docs/manual/api.html#non-qt-python-programs) and [PDF](https://veusz.github.io/docs/manual.pdf) versions of docs, when only two backslashes are wanted.
The second fix is adding the y axis label, which was missed from the new style code block.
p.s. Thanks ever so much for developing Veusz. I've used it for many years and think it's fantastic.
=> Minor fixes for api.rst

veusz/widgets/boxplot.py
Fixed calculation of bottom whisker in '1.5IQR' mode. Now effectivly
rounding up instead of down.
Closes #449
=> Bugfix for boxplot

pyqtdistutils.py
Sort input file list
so that `veusz/helpers/qtloops.cpython-38-x86_64-linux-gnu.so` builds in a reproducible way
in spite of indeterministic filesystem readdir order
See https://reproducible-builds.org/ for why this is good.
=> Sort input file list

veusz/document/mime.py, veusz/widgets/shape.py, veusz/windows/treeeditwindow.py
This pull request is an answer to https://github.com/veusz/veusz/issues/395#issue-589261447
This update enables
- copying a plot page to the clipboard as images
- pasting an clipboard image on the plot page.
I think it would be useful when users want to frequently exchange images with other software.
- "Copy as Image" menu appears when a user right click on the tree edit window.
- "Ctrl + Alt + C" is assigned to the shortcut of this action.
- DPI and other parameters depend on the settings of usual "export".
- "Copy as Image" exports the selected page as 3 types of images, and copies them to clipboard as 4 types of mime data
- "image/svg+xml" (.svg)
- "image/png" (.png)
- "PNG" (.png)
- "image/x-bmp" (.bmp)
- I checked that either of the 4 mime type can be pasted to major software, as …
=> Enabling copy and paste as image

veusz/helpers/src/qtloops/beziers_qtwrap.cpp, veusz/helpers/src/qtloops/beziers_qtwrap.h, veusz/helpers/src/qtloops/qtloops.sip, veusz/setting/collections.py, veusz/widgets/point.py
- Issue #547
- `PlotLine/bezierJoin` sometimes gives too loose curves.
- Existing Bezier-fit was renamed to "loose-Bezier", and "tight-Bezier" was newly added.
- Core function `bezier_fit_cubic_tight` in beziers_qtwrap.cpp was added.
- The algorithm is based on an Excel-like cubic Bezier fitting formulated by Brian Murphy (http://www.xlrotor.com/Smooth_curve_bezier_example_file.zip). 
- 4 bezier control points (ctrls[0]-ctrl[3]) are created for each line segment. Positions of ctrls are determined by 4 nearest data points (pt0-pt3) with following rules:
1. ctrls[0]: same position as pt0.
2. ctrls[1]: on a line through pt1 parallel to pt0-pt2, at a distance from pt1 = f1 * |pt0-pt2|
3. ctrls[2]: on a line through pt2 parallel to pt1-pt3, at a distance from pt2 = f2 * |pt1-pt3|
4. ctrls[3]: …
=> Improvement of Bezier join

INSTALL, README.md, pyqtdistutils.py, requirements.txt
This adds support for the latest SIP versions (6.x) but removes support for SIP v4.
Background:
- SIP 5.0.0 was released on 2019-10-08.
- SIP 6.0.0 was released on 2021-01-04.
- SIP developer [wrote](https://www.riverbankcomputing.com/pipermail/pyqt/2020-September/043162.html) in September 2020:
> SIP v4 has been deprecated for more than a year. *Nobody* should still be using it.
- In #433 I added support for SIP v5. The code used `sip5` legacy tool that was present in SIP v5 for compatibility with v4.
- In SIP v6, that tool is not present. So we have two ways: either use SIP's own buildsystem (`sip-build` command-line tool), or use the `sipbuild` API from Python. Here I went with the second approach.
To test this, try installing the latest versions of `sip`, `PyQt5` and `PyQt5.sip` from …
=> Use sipbuild API instead of invoking sip as a subprocess

veusz/setting/controls.py
- Set `+` `-` `..` buttons padding to 0 to  make them visible on recent macOS
- Related issues: 
- #570
- #602
- on macOS 12
- on macOS 12
- on MS Windows 10
- on Ubuntu 22
- `setAttribute(qt.Qt.WA_LayoutUsesWidgetRect)` was not effective.
- Remained issue: Clickable area is too small on macOS.
By mofifying `margin` value and/or `QSizePolicy`, I have managed to find the condition to solve this clickable area issue on macOS. But these modifications make appearances on Windows and/or Linux incorrect. I have not yet found a setting to make appearance correct on the all three so far.
=> Fix +, -, .. button appearance issue on macOS

veusz/plugins/datasetplugin.py
For issue https://github.com/veusz/veusz/issues/655
Update a deprecated `numpy.histogram2d()` keyword `normed` to the new keyword `density`.
=> change histgram2d() arg from 'normed' to 'density'

veusz/datasets/nd.py
The `object` parameter of `numpy.array` was missing. I assume it should be `data`.
=> Fix loosing `data` when it's not a numpy array

veusz/widgets/histo.py
`Histo.perrs` and `Histo.nerrs` are sometimes called `Histo.perr` and `Histo.nerr`, respectfully. Use the same attribute throughout the class.
=> Fix typos in `nerrs` and `perrs` attribute names

veusz/dataimport/simpleread.py
Swap `self.xcent` and `self.ycent`, as well as `self.xedge` and `self.yedge`, for 2D data import with Transpose option. (#692)
=> Minor fixes for 2D data import with Transpose option

veusz/document/mime.py
When one has added an image to a plot by pasting, the image is automatically embedded, and there is no straightforward way to de-embed that image (say, if you want to modify it, or copy it elsewhere, without having to look for its source).
This simple patch puts the images back onto the clipboard.
=> When copying svgfile or imagefile widgets, also put images themselves on clipboard.

veusz/windows/treeeditwindow.py
On macOS, the `FormatDock` tabs are overlapping with the dock title bar.
The `QTabWidget` is now added within a `QVBoxLayout`, which is then set as the layout of a container widget inside the `QDockWidget`. This change avoids placing the tab widget directly in the dock, which caused the overlap.
Tabs are rendered on top of the dock title bar:
=> bugfix: Overlapping of FormatDock tabs on the titlebar

veusz/windows/treeeditwindow.py
Related to https://github.com/veusz/veusz/pull/749
A blank area appears in the formatting dock after removing an object.
Just removing the `tabWidget` is not enough to refresh it.
Use `takeAt()` to explicitly take out an old tab widget from the layout.
I'm sorry for bothering you.
=> bugfix: Explicitly take out an old tab widget from layout

pyqt_setuptools.py
Hi,
On Debian we are trying to slowly remove old libraries/backports.
`tomli` lives on in the standard library as `tomllib` from Python 3.11
https://wiki.debian.org/Python/Backports
=> prefer newer "tomllib" on Python3.11 and higher
